### ISSUE TITLE
Orbit run kickoff - ValueError: dictionary update sequence element #0 has length 20; 2 is required

### ISSUE THREAD

**Issue by Abdelrhman-Allam** [gulien/orbit#21]
Hello, 
please check the error I found while doing run for the command 

vagrant@homestead:~/Code/priips$ sudo orbit run kickoff
Setting UID (0) to "www-data" user in Docker Sync configuration file ...
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 768, in run
  File "compose/cli/main.py", line 1178, in run_one_off_container
  File "compose/service.py", line 288, in create_container
  File "compose/service.py", line 795, in _get_container_create_options
  File "compose/service.py", line 1338, in build_container_labels
ValueError: dictionary update sequence element #0 has length 20; 2 is required
Failed to execute script docker-compose

this run inside vagrant machine

**Comment by Abdelrhman-Allam** [comment]
Resolved/fixed 
downgrade from docker-compose 1.17.0 to 1.14.0

**Comment by gulien** [comment]
Sorry for the late answer!

For the kickoff project, you should never use root user (nor sudo) :-)
